// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: protos/registry.proto

package registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	PortNumber    string                 `protobuf:"bytes,3,opt,name=portNumber,proto3" json:"portNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_protos_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterNodeRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterNodeRequest) GetPortNumber() string {
	if x != nil {
		return x.PortNumber
	}
	return ""
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_protos_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PrimaryNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimaryNodeRequest) Reset() {
	*x = PrimaryNodeRequest{}
	mi := &file_protos_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryNodeRequest) ProtoMessage() {}

func (x *PrimaryNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryNodeRequest.ProtoReflect.Descriptor instead.
func (*PrimaryNodeRequest) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{2}
}

type PrimaryNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	PortNumber    string                 `protobuf:"bytes,3,opt,name=portNumber,proto3" json:"portNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimaryNodeResponse) Reset() {
	*x = PrimaryNodeResponse{}
	mi := &file_protos_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryNodeResponse) ProtoMessage() {}

func (x *PrimaryNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryNodeResponse.ProtoReflect.Descriptor instead.
func (*PrimaryNodeResponse) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{3}
}

func (x *PrimaryNodeResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PrimaryNodeResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *PrimaryNodeResponse) GetPortNumber() string {
	if x != nil {
		return x.PortNumber
	}
	return ""
}

var File_protos_registry_proto protoreflect.FileDescriptor

const file_protos_registry_proto_rawDesc = "" +
	"\n" +
	"\x15protos/registry.proto\x12\bregistry\"o\n" +
	"\x13RegisterNodeRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\x12\x1e\n" +
	"\n" +
	"portNumber\x18\x03 \x01(\tR\n" +
	"portNumber\"H\n" +
	"\x14RegisterNodeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12PrimaryNodeRequest\"o\n" +
	"\x13PrimaryNodeResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\x12\x1e\n" +
	"\n" +
	"portNumber\x18\x03 \x01(\tR\n" +
	"portNumber2\xaf\x01\n" +
	"\x0fRegistryService\x12M\n" +
	"\fRegisterNode\x12\x1d.registry.RegisterNodeRequest\x1a\x1e.registry.RegisterNodeResponse\x12M\n" +
	"\x0eGetPrimaryNode\x12\x1c.registry.PrimaryNodeRequest\x1a\x1d.registry.PrimaryNodeResponseB%Z#github.com/Vahsek/distrokv/registryb\x06proto3"

var (
	file_protos_registry_proto_rawDescOnce sync.Once
	file_protos_registry_proto_rawDescData []byte
)

func file_protos_registry_proto_rawDescGZIP() []byte {
	file_protos_registry_proto_rawDescOnce.Do(func() {
		file_protos_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_registry_proto_rawDesc), len(file_protos_registry_proto_rawDesc)))
	})
	return file_protos_registry_proto_rawDescData
}

var file_protos_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_registry_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),  // 0: registry.RegisterNodeRequest
	(*RegisterNodeResponse)(nil), // 1: registry.RegisterNodeResponse
	(*PrimaryNodeRequest)(nil),   // 2: registry.PrimaryNodeRequest
	(*PrimaryNodeResponse)(nil),  // 3: registry.PrimaryNodeResponse
}
var file_protos_registry_proto_depIdxs = []int32{
	0, // 0: registry.RegistryService.RegisterNode:input_type -> registry.RegisterNodeRequest
	2, // 1: registry.RegistryService.GetPrimaryNode:input_type -> registry.PrimaryNodeRequest
	1, // 2: registry.RegistryService.RegisterNode:output_type -> registry.RegisterNodeResponse
	3, // 3: registry.RegistryService.GetPrimaryNode:output_type -> registry.PrimaryNodeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_registry_proto_init() }
func file_protos_registry_proto_init() {
	if File_protos_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_registry_proto_rawDesc), len(file_protos_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_registry_proto_goTypes,
		DependencyIndexes: file_protos_registry_proto_depIdxs,
		MessageInfos:      file_protos_registry_proto_msgTypes,
	}.Build()
	File_protos_registry_proto = out.File
	file_protos_registry_proto_goTypes = nil
	file_protos_registry_proto_depIdxs = nil
}
