// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: protos/registry.proto

package registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	PortNumber    string                 `protobuf:"bytes,3,opt,name=portNumber,proto3" json:"portNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_protos_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterNodeRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterNodeRequest) GetPortNumber() string {
	if x != nil {
		return x.PortNumber
	}
	return ""
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_protos_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PrimaryNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimaryNodeRequest) Reset() {
	*x = PrimaryNodeRequest{}
	mi := &file_protos_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryNodeRequest) ProtoMessage() {}

func (x *PrimaryNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryNodeRequest.ProtoReflect.Descriptor instead.
func (*PrimaryNodeRequest) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{2}
}

type PrimaryNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	PortNumber    string                 `protobuf:"bytes,3,opt,name=portNumber,proto3" json:"portNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimaryNodeResponse) Reset() {
	*x = PrimaryNodeResponse{}
	mi := &file_protos_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryNodeResponse) ProtoMessage() {}

func (x *PrimaryNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryNodeResponse.ProtoReflect.Descriptor instead.
func (*PrimaryNodeResponse) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{3}
}

func (x *PrimaryNodeResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PrimaryNodeResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *PrimaryNodeResponse) GetPortNumber() string {
	if x != nil {
		return x.PortNumber
	}
	return ""
}

type HeartBeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	PortNumber    string                 `protobuf:"bytes,3,opt,name=portNumber,proto3" json:"portNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatRequest) Reset() {
	*x = HeartBeatRequest{}
	mi := &file_protos_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRequest) ProtoMessage() {}

func (x *HeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{4}
}

func (x *HeartBeatRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HeartBeatRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *HeartBeatRequest) GetPortNumber() string {
	if x != nil {
		return x.PortNumber
	}
	return ""
}

type HeartBeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	mi := &file_protos_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{5}
}

func (x *HeartBeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartBeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NodeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListRequest) Reset() {
	*x = NodeListRequest{}
	mi := &file_protos_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListRequest) ProtoMessage() {}

func (x *NodeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListRequest.ProtoReflect.Descriptor instead.
func (*NodeListRequest) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{6}
}

type NodeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeList      []*NodeDetails         `protobuf:"bytes,1,rep,name=nodeList,proto3" json:"nodeList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListResponse) Reset() {
	*x = NodeListResponse{}
	mi := &file_protos_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListResponse) ProtoMessage() {}

func (x *NodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListResponse.ProtoReflect.Descriptor instead.
func (*NodeListResponse) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{7}
}

func (x *NodeListResponse) GetNodeList() []*NodeDetails {
	if x != nil {
		return x.NodeList
	}
	return nil
}

type NodeDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeIP          string                 `protobuf:"bytes,1,opt,name=nodeIP,proto3" json:"nodeIP,omitempty"`
	NodeHostname    string                 `protobuf:"bytes,2,opt,name=nodeHostname,proto3" json:"nodeHostname,omitempty"`
	NodeControlPort string                 `protobuf:"bytes,3,opt,name=nodeControlPort,proto3" json:"nodeControlPort,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeDetails) Reset() {
	*x = NodeDetails{}
	mi := &file_protos_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDetails) ProtoMessage() {}

func (x *NodeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_protos_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDetails.ProtoReflect.Descriptor instead.
func (*NodeDetails) Descriptor() ([]byte, []int) {
	return file_protos_registry_proto_rawDescGZIP(), []int{8}
}

func (x *NodeDetails) GetNodeIP() string {
	if x != nil {
		return x.NodeIP
	}
	return ""
}

func (x *NodeDetails) GetNodeHostname() string {
	if x != nil {
		return x.NodeHostname
	}
	return ""
}

func (x *NodeDetails) GetNodeControlPort() string {
	if x != nil {
		return x.NodeControlPort
	}
	return ""
}

var File_protos_registry_proto protoreflect.FileDescriptor

const file_protos_registry_proto_rawDesc = "" +
	"\n" +
	"\x15protos/registry.proto\x12\bregistry\"o\n" +
	"\x13RegisterNodeRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\x12\x1e\n" +
	"\n" +
	"portNumber\x18\x03 \x01(\tR\n" +
	"portNumber\"H\n" +
	"\x14RegisterNodeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12PrimaryNodeRequest\"o\n" +
	"\x13PrimaryNodeResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\x12\x1e\n" +
	"\n" +
	"portNumber\x18\x03 \x01(\tR\n" +
	"portNumber\"l\n" +
	"\x10HeartBeatRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\x12\x1e\n" +
	"\n" +
	"portNumber\x18\x03 \x01(\tR\n" +
	"portNumber\"E\n" +
	"\x11HeartBeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fNodeListRequest\"E\n" +
	"\x10NodeListResponse\x121\n" +
	"\bnodeList\x18\x01 \x03(\v2\x15.registry.NodeDetailsR\bnodeList\"s\n" +
	"\vNodeDetails\x12\x16\n" +
	"\x06nodeIP\x18\x01 \x01(\tR\x06nodeIP\x12\"\n" +
	"\fnodeHostname\x18\x02 \x01(\tR\fnodeHostname\x12(\n" +
	"\x0fnodeControlPort\x18\x03 \x01(\tR\x0fnodeControlPort2\xbf\x02\n" +
	"\x0fRegistryService\x12M\n" +
	"\fRegisterNode\x12\x1d.registry.RegisterNodeRequest\x1a\x1e.registry.RegisterNodeResponse\x12M\n" +
	"\x0eGetPrimaryNode\x12\x1c.registry.PrimaryNodeRequest\x1a\x1d.registry.PrimaryNodeResponse\x12H\n" +
	"\rNodeHeartBeat\x12\x1a.registry.HeartBeatRequest\x1a\x1b.registry.HeartBeatResponse\x12D\n" +
	"\vGetNodeList\x12\x19.registry.NodeListRequest\x1a\x1a.registry.NodeListResponseB)Z'github.com/Vahsek/distrokv/pkg/registryb\x06proto3"

var (
	file_protos_registry_proto_rawDescOnce sync.Once
	file_protos_registry_proto_rawDescData []byte
)

func file_protos_registry_proto_rawDescGZIP() []byte {
	file_protos_registry_proto_rawDescOnce.Do(func() {
		file_protos_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_registry_proto_rawDesc), len(file_protos_registry_proto_rawDesc)))
	})
	return file_protos_registry_proto_rawDescData
}

var file_protos_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_registry_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),  // 0: registry.RegisterNodeRequest
	(*RegisterNodeResponse)(nil), // 1: registry.RegisterNodeResponse
	(*PrimaryNodeRequest)(nil),   // 2: registry.PrimaryNodeRequest
	(*PrimaryNodeResponse)(nil),  // 3: registry.PrimaryNodeResponse
	(*HeartBeatRequest)(nil),     // 4: registry.HeartBeatRequest
	(*HeartBeatResponse)(nil),    // 5: registry.HeartBeatResponse
	(*NodeListRequest)(nil),      // 6: registry.NodeListRequest
	(*NodeListResponse)(nil),     // 7: registry.NodeListResponse
	(*NodeDetails)(nil),          // 8: registry.NodeDetails
}
var file_protos_registry_proto_depIdxs = []int32{
	8, // 0: registry.NodeListResponse.nodeList:type_name -> registry.NodeDetails
	0, // 1: registry.RegistryService.RegisterNode:input_type -> registry.RegisterNodeRequest
	2, // 2: registry.RegistryService.GetPrimaryNode:input_type -> registry.PrimaryNodeRequest
	4, // 3: registry.RegistryService.NodeHeartBeat:input_type -> registry.HeartBeatRequest
	6, // 4: registry.RegistryService.GetNodeList:input_type -> registry.NodeListRequest
	1, // 5: registry.RegistryService.RegisterNode:output_type -> registry.RegisterNodeResponse
	3, // 6: registry.RegistryService.GetPrimaryNode:output_type -> registry.PrimaryNodeResponse
	5, // 7: registry.RegistryService.NodeHeartBeat:output_type -> registry.HeartBeatResponse
	7, // 8: registry.RegistryService.GetNodeList:output_type -> registry.NodeListResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_registry_proto_init() }
func file_protos_registry_proto_init() {
	if File_protos_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_registry_proto_rawDesc), len(file_protos_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_registry_proto_goTypes,
		DependencyIndexes: file_protos_registry_proto_depIdxs,
		MessageInfos:      file_protos_registry_proto_msgTypes,
	}.Build()
	File_protos_registry_proto = out.File
	file_protos_registry_proto_goTypes = nil
	file_protos_registry_proto_depIdxs = nil
}
