// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: protos/NodeControlPlane.proto

package controlplane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetReplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReplicationRequest) Reset() {
	*x = SetReplicationRequest{}
	mi := &file_protos_NodeControlPlane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReplicationRequest) ProtoMessage() {}

func (x *SetReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_NodeControlPlane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReplicationRequest.ProtoReflect.Descriptor instead.
func (*SetReplicationRequest) Descriptor() ([]byte, []int) {
	return file_protos_NodeControlPlane_proto_rawDescGZIP(), []int{0}
}

func (x *SetReplicationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetReplicationRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReplicationResponse) Reset() {
	*x = SetReplicationResponse{}
	mi := &file_protos_NodeControlPlane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReplicationResponse) ProtoMessage() {}

func (x *SetReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_NodeControlPlane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReplicationResponse.ProtoReflect.Descriptor instead.
func (*SetReplicationResponse) Descriptor() ([]byte, []int) {
	return file_protos_NodeControlPlane_proto_rawDescGZIP(), []int{1}
}

func (x *SetReplicationResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetReplicationResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *SetReplicationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteReplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplicationRequest) Reset() {
	*x = DeleteReplicationRequest{}
	mi := &file_protos_NodeControlPlane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplicationRequest) ProtoMessage() {}

func (x *DeleteReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_NodeControlPlane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplicationRequest) Descriptor() ([]byte, []int) {
	return file_protos_NodeControlPlane_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteReplicationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplicationResponse) Reset() {
	*x = DeleteReplicationResponse{}
	mi := &file_protos_NodeControlPlane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplicationResponse) ProtoMessage() {}

func (x *DeleteReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_NodeControlPlane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplicationResponse.ProtoReflect.Descriptor instead.
func (*DeleteReplicationResponse) Descriptor() ([]byte, []int) {
	return file_protos_NodeControlPlane_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteReplicationResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteReplicationResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DeleteReplicationResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeleteReplicationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NewServerAddRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hostname         string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress        string                 `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	ControlPlanePort string                 `protobuf:"bytes,3,opt,name=controlPlanePort,proto3" json:"controlPlanePort,omitempty"`
	DataPlanePort    string                 `protobuf:"bytes,4,opt,name=dataPlanePort,proto3" json:"dataPlanePort,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NewServerAddRequest) Reset() {
	*x = NewServerAddRequest{}
	mi := &file_protos_NodeControlPlane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewServerAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewServerAddRequest) ProtoMessage() {}

func (x *NewServerAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_NodeControlPlane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewServerAddRequest.ProtoReflect.Descriptor instead.
func (*NewServerAddRequest) Descriptor() ([]byte, []int) {
	return file_protos_NodeControlPlane_proto_rawDescGZIP(), []int{4}
}

func (x *NewServerAddRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NewServerAddRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NewServerAddRequest) GetControlPlanePort() string {
	if x != nil {
		return x.ControlPlanePort
	}
	return ""
}

func (x *NewServerAddRequest) GetDataPlanePort() string {
	if x != nil {
		return x.DataPlanePort
	}
	return ""
}

type NewServerAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewServerAddResponse) Reset() {
	*x = NewServerAddResponse{}
	mi := &file_protos_NodeControlPlane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewServerAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewServerAddResponse) ProtoMessage() {}

func (x *NewServerAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_NodeControlPlane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewServerAddResponse.ProtoReflect.Descriptor instead.
func (*NewServerAddResponse) Descriptor() ([]byte, []int) {
	return file_protos_NodeControlPlane_proto_rawDescGZIP(), []int{5}
}

func (x *NewServerAddResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NewServerAddResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_NodeControlPlane_proto protoreflect.FileDescriptor

const file_protos_NodeControlPlane_proto_rawDesc = "" +
	"\n" +
	"\x1dprotos/NodeControlPlane.proto\x12\x10nodecontrolplane\"?\n" +
	"\x15SetReplicationRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"X\n" +
	"\x16SetReplicationResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\",\n" +
	"\x18DeleteReplicationRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"q\n" +
	"\x19DeleteReplicationResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xa1\x01\n" +
	"\x13NewServerAddRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\x12*\n" +
	"\x10controlPlanePort\x18\x03 \x01(\tR\x10controlPlanePort\x12$\n" +
	"\rdataPlanePort\x18\x04 \x01(\tR\rdataPlanePort\"H\n" +
	"\x14NewServerAddResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xde\x02\n" +
	"\x17NodeControlPlaneService\x12h\n" +
	"\x13ReplicateSetRequest\x12'.nodecontrolplane.SetReplicationRequest\x1a(.nodecontrolplane.SetReplicationResponse\x12q\n" +
	"\x16ReplicateDeleteRequest\x12*.nodecontrolplane.DeleteReplicationRequest\x1a+.nodecontrolplane.DeleteReplicationResponse\x12f\n" +
	"\x15RegisterNewPeerServer\x12%.nodecontrolplane.NewServerAddRequest\x1a&.nodecontrolplane.NewServerAddResponseB2Z0github.com/Vahsek/distrokv/pkg/node/controlplaneb\x06proto3"

var (
	file_protos_NodeControlPlane_proto_rawDescOnce sync.Once
	file_protos_NodeControlPlane_proto_rawDescData []byte
)

func file_protos_NodeControlPlane_proto_rawDescGZIP() []byte {
	file_protos_NodeControlPlane_proto_rawDescOnce.Do(func() {
		file_protos_NodeControlPlane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_NodeControlPlane_proto_rawDesc), len(file_protos_NodeControlPlane_proto_rawDesc)))
	})
	return file_protos_NodeControlPlane_proto_rawDescData
}

var file_protos_NodeControlPlane_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_NodeControlPlane_proto_goTypes = []any{
	(*SetReplicationRequest)(nil),     // 0: nodecontrolplane.SetReplicationRequest
	(*SetReplicationResponse)(nil),    // 1: nodecontrolplane.SetReplicationResponse
	(*DeleteReplicationRequest)(nil),  // 2: nodecontrolplane.DeleteReplicationRequest
	(*DeleteReplicationResponse)(nil), // 3: nodecontrolplane.DeleteReplicationResponse
	(*NewServerAddRequest)(nil),       // 4: nodecontrolplane.NewServerAddRequest
	(*NewServerAddResponse)(nil),      // 5: nodecontrolplane.NewServerAddResponse
}
var file_protos_NodeControlPlane_proto_depIdxs = []int32{
	0, // 0: nodecontrolplane.NodeControlPlaneService.ReplicateSetRequest:input_type -> nodecontrolplane.SetReplicationRequest
	2, // 1: nodecontrolplane.NodeControlPlaneService.ReplicateDeleteRequest:input_type -> nodecontrolplane.DeleteReplicationRequest
	4, // 2: nodecontrolplane.NodeControlPlaneService.RegisterNewPeerServer:input_type -> nodecontrolplane.NewServerAddRequest
	1, // 3: nodecontrolplane.NodeControlPlaneService.ReplicateSetRequest:output_type -> nodecontrolplane.SetReplicationResponse
	3, // 4: nodecontrolplane.NodeControlPlaneService.ReplicateDeleteRequest:output_type -> nodecontrolplane.DeleteReplicationResponse
	5, // 5: nodecontrolplane.NodeControlPlaneService.RegisterNewPeerServer:output_type -> nodecontrolplane.NewServerAddResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_NodeControlPlane_proto_init() }
func file_protos_NodeControlPlane_proto_init() {
	if File_protos_NodeControlPlane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_NodeControlPlane_proto_rawDesc), len(file_protos_NodeControlPlane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_NodeControlPlane_proto_goTypes,
		DependencyIndexes: file_protos_NodeControlPlane_proto_depIdxs,
		MessageInfos:      file_protos_NodeControlPlane_proto_msgTypes,
	}.Build()
	File_protos_NodeControlPlane_proto = out.File
	file_protos_NodeControlPlane_proto_goTypes = nil
	file_protos_NodeControlPlane_proto_depIdxs = nil
}
