// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: protos/NodeKV.proto

package dataplane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeKeyValueService_GetKey_FullMethodName    = "/nodedataplane.NodeKeyValueService/GetKey"
	NodeKeyValueService_SetKey_FullMethodName    = "/nodedataplane.NodeKeyValueService/SetKey"
	NodeKeyValueService_DeleteKey_FullMethodName = "/nodedataplane.NodeKeyValueService/DeleteKey"
)

// NodeKeyValueServiceClient is the client API for NodeKeyValueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeKeyValueServiceClient interface {
	GetKey(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	SetKey(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	DeleteKey(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type nodeKeyValueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeKeyValueServiceClient(cc grpc.ClientConnInterface) NodeKeyValueServiceClient {
	return &nodeKeyValueServiceClient{cc}
}

func (c *nodeKeyValueServiceClient) GetKey(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, NodeKeyValueService_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeKeyValueServiceClient) SetKey(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, NodeKeyValueService_SetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeKeyValueServiceClient) DeleteKey(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, NodeKeyValueService_DeleteKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeKeyValueServiceServer is the server API for NodeKeyValueService service.
// All implementations must embed UnimplementedNodeKeyValueServiceServer
// for forward compatibility.
type NodeKeyValueServiceServer interface {
	GetKey(context.Context, *GetRequest) (*GetResponse, error)
	SetKey(context.Context, *SetRequest) (*SetResponse, error)
	DeleteKey(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedNodeKeyValueServiceServer()
}

// UnimplementedNodeKeyValueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeKeyValueServiceServer struct{}

func (UnimplementedNodeKeyValueServiceServer) GetKey(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedNodeKeyValueServiceServer) SetKey(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetKey not implemented")
}
func (UnimplementedNodeKeyValueServiceServer) DeleteKey(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKey not implemented")
}
func (UnimplementedNodeKeyValueServiceServer) mustEmbedUnimplementedNodeKeyValueServiceServer() {}
func (UnimplementedNodeKeyValueServiceServer) testEmbeddedByValue()                             {}

// UnsafeNodeKeyValueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeKeyValueServiceServer will
// result in compilation errors.
type UnsafeNodeKeyValueServiceServer interface {
	mustEmbedUnimplementedNodeKeyValueServiceServer()
}

func RegisterNodeKeyValueServiceServer(s grpc.ServiceRegistrar, srv NodeKeyValueServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeKeyValueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeKeyValueService_ServiceDesc, srv)
}

func _NodeKeyValueService_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeKeyValueServiceServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeKeyValueService_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeKeyValueServiceServer).GetKey(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeKeyValueService_SetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeKeyValueServiceServer).SetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeKeyValueService_SetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeKeyValueServiceServer).SetKey(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeKeyValueService_DeleteKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeKeyValueServiceServer).DeleteKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeKeyValueService_DeleteKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeKeyValueServiceServer).DeleteKey(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeKeyValueService_ServiceDesc is the grpc.ServiceDesc for NodeKeyValueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeKeyValueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodedataplane.NodeKeyValueService",
	HandlerType: (*NodeKeyValueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKey",
			Handler:    _NodeKeyValueService_GetKey_Handler,
		},
		{
			MethodName: "SetKey",
			Handler:    _NodeKeyValueService_SetKey_Handler,
		},
		{
			MethodName: "DeleteKey",
			Handler:    _NodeKeyValueService_DeleteKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/NodeKV.proto",
}
